# IMDb Movies Dataset — Exploratory Data Analysis

Bu notebook, `data/imdb.csv` dosyasını **pandas** ile okuyup veri setini tanımak (EDA) için hazırlanmıştır.

## Kurulum ve İçe Aktarım

- `pandas`: tablo verileri (DataFrame) ile çalışma
- İsteğe bağlı olarak görüntülemeyi daha rahat yapmak için bazı ayarlar

In [2]:
import pandas as pd

# Görünüm ayarları (opsiyonel)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 140)

- **pandas**, veri analizi için kullanılan temel Python kütüphanesidir.
- `pd` takma adıyla çağrılır (standart kullanım).
- Pandas kütüphanesinde yoğun olarak kullanılan veri tipi 'Series' ve 'Dataframe'.

---

## Veri Okuma

`pd.read_csv()` ile CSV dosyasını DataFrame'e çeviriyoruz.

> Not: Dosya yolu projedeki konuma göre değişebilir.

In [3]:
df = pd.read_csv("data/imdb.csv")
df

                                           Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID             Record  Runtime
0                                    Code Name: K.O.Z.         2015     1.4        24623  tt4458206  Bottom 250 Movies    114.0
1                                     Saving Christmas         2014     1.5        12765  tt4009460  Bottom 250 Movies     80.0
2                         Superbabies: Baby Geniuses 2         2004     1.6        26505  tt0270846  Bottom 250 Movies     88.0
3                                    Daniel the Wizard         2004     1.6        13295  tt0421051  Bottom 250 Movies     81.0
4                             Manos: The Hands of Fate         1966     1.7        31808  tt0060666  Bottom 250 Movies     70.0
..                                                 ...          ...     ...          ...        ...                ...      ...
845  Pirates of the Caribbean: The Curse of the Bla...         2003     8.0       872441  tt0325980     Top 250 Movies    143.0
846                   What Ever Happened to Baby Jane?         1962     8.0        37906  tt0056687     Top 250 Movies    134.0
847                                       Paris, Texas         1984     8.0        55587  tt0087884     Top 250 Movies    145.0
848                                           Drishyam         2015     8.0        40777  tt4430212     Top 250 Movies    163.0
849                                                 PK         2014     8.0       106375  tt2338151     Top 250 Movies    153.0

[850 rows x 7 columns]

- `read_csv()` → CSV dosyasını okuyup **DataFrame** oluşturur.
- `data/imdb.csv` → Dosyanın bulunduğu yol.
- Sonuç **df** adlı bir DataFrame’e atanır.

📌 Bu DataFrame IMDb film verilerini içeriyor.

---

## İlk / Son Kayıtları İnceleme

Verinin yapısını hızlıca görmek için:
- `head()` → ilk 5 satır
- `tail()` → son 5 satır

### İlk 5 Satırı Görüntüleme

`head` fonksiyonu, veri setimizin argüman değeri kadar satrını bize döner.

default değeri 5'tir. 

Bir argüman girmezsek veri setinin ilk 5 satırını bize döndürür.

In [74]:
df.head()

                    Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID             Record  Runtime
0             Code Name: K.O.Z.         2015     1.4        24623  tt4458206  Bottom 250 Movies    114.0
1              Saving Christmas         2014     1.5        12765  tt4009460  Bottom 250 Movies     80.0
2  Superbabies: Baby Geniuses 2         2004     1.6        26505  tt0270846  Bottom 250 Movies     88.0
3             Daniel the Wizard         2004     1.6        13295  tt0421051  Bottom 250 Movies     81.0
4      Manos: The Hands of Fate         1966     1.7        31808  tt0060666  Bottom 250 Movies     70.0

- DataFrame’in ilk 5 satırını gösterir.
- Veri yapısını hızlıca görmek için kullanılır.

---

### Son 5 Satırı Görüntüleme

`head` fonksiyonunun tam tersi olarak çalışır. 

Argüman değeri kadar satırı sondan bize döndürür.

In [79]:
df.tail()

                                           Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID          Record  Runtime
845  Pirates of the Caribbean: The Curse of the Bla...         2003     8.0       872441  tt0325980  Top 250 Movies    143.0
846                   What Ever Happened to Baby Jane?         1962     8.0        37906  tt0056687  Top 250 Movies    134.0
847                                       Paris, Texas         1984     8.0        55587  tt0087884  Top 250 Movies    145.0
848                                           Drishyam         2015     8.0        40777  tt4430212  Top 250 Movies    163.0
849                                                 PK         2014     8.0       106375  tt2338151  Top 250 Movies    153.0

- DataFrame’in **son 5 satırını** gösterir.
- Verinin sonunun düzgün yüklenip yüklenmediğini kontrol etmek için kullanılır.

---

## Boyut (Shape)

`df.shape` bize **(satır, sütun)** bilgisini verir.

- Satır = kaç kayıt (film) var?
- Sütun = kaç özellik (kolon) var?

In [80]:
df.shape

(850, 7)

Çıktı formatı:
`(satır_sayısı, sütun_sayısı)`

---

## Sütun İsimleri

`df.columns` ile sütun isimlerini listeleriz.  
Bu, özellikle veri temizliği ve isimlendirme kontrolü için önemlidir.

In [77]:
df.columns

Index(['Movie_Title', 'YR_Released', 'Rating', 'Num_Reviews', 'Movie_ID', 'Record', 'Runtime'], dtype='object')

📌 `dtype='object'` → Bu **Index** nesnesinin tipi (string liste gibi düşünebilirsin)

---

## Ham Değerler (NumPy Array) — `df.values`

`df.values` DataFrame'in içindeki değerleri **NumPy array** olarak verir.

- Sütun isimleri ve index **yoktur**
- Çoğu EDA aşamasında gerekmez, ama:
  - Makine öğrenmesi
  - NumPy tabanlı işlemler
  - Performans odaklı hesaplar  
için kullanılabilir.

⚠️ Günlük analizlerde genelde **kullanılmaz**, çünkü:
- Okunabilir değil
- Sütun isimleri kaybolur

In [81]:
df.values

array([['Code Name: K.O.Z.', 2015, 1.4, ..., 'tt4458206',
        'Bottom 250 Movies', 114.0],
       ['Saving Christmas', 2014, 1.5, ..., 'tt4009460',
        'Bottom 250 Movies', 80.0],
       ['Superbabies: Baby Geniuses 2', 2004, 1.6, ..., 'tt0270846',
        'Bottom 250 Movies', 88.0],
       ...,
       ['Paris, Texas', 1984, 8.0, ..., 'tt0087884', 'Top 250 Movies',
        145.0],
       ['Drishyam', 2015, 8.0, ..., 'tt4430212', 'Top 250 Movies', 163.0],
       ['PK', 2014, 8.0, ..., 'tt2338151', 'Top 250 Movies', 153.0]],
      dtype=object)

- DataFrame’in **ham NumPy array** halini döndürür.
- Çıktı:
    - 2 boyutlu bir liste (`list of lists` gibi)
    - Sütun isimleri **yok**
    - Sadece **değerler** var

---

## İstatistiksel Özet — `df.describe()`

`describe()` sayısal sütunlar için hızlı bir özet verir:

- count: dolu değer sayısı
- mean: ortalama
- std: standart sapma
- min / max: en küçük / en büyük
- 25% / 50% / 75%: çeyrekler (quartiles), 50% = medyan

In [82]:
df.describe()

       YR_Released      Rating   Num_Reviews     Runtime
count   850.000000  850.000000  8.500000e+02  849.000000
mean   1991.375294    7.371882  2.593526e+05  130.771496
std      22.855960    1.886546  3.469407e+05   33.232523
min    1921.000000    1.400000  0.000000e+00   54.000000
25%    1977.250000    7.500000  1.242750e+04  105.000000
50%    1999.000000    8.100000  7.861750e+04  129.000000
75%    2009.000000    8.200000  4.437150e+05  153.000000
max    2017.000000    9.200000  1.829037e+06  320.000000

**Ne yapar?**
- **Sadece sayısal sütunlar** için
- İstatistiksel özet üretir

---

## Yapısal Özet — `df.info()`

`info()` DataFrame'in kimlik kartıdır:

- satır sayısı
- her sütunun **veri tipi (dtype)**
- her sütunda kaç **non-null** değer var (eksik veri kontrolü için çok kritik)
- bellek kullanımı

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Movie_Title  850 non-null    object
 1   YR_Released  850 non-null    int64
 2   Rating       850 non-null    float64
 3   Num_Reviews  850 non-null    int64
 4   Movie_ID     850 non-null    object
 5   Record       850 non-null    object
 6   Runtime      849 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 46.6+ KB

Yapısal bilgi verir

`Veri tipi + eksik veri`

---

## Eksik Veri Analizi

Eksik veri (NaN) analizi için en pratik komutlardan biri:

- `df.isnull()` → True/False tablosu döndürür  
- `.sum()` → True değerleri sayar (yani NaN sayısı)

Sonuç bize her sütunda kaç eksik veri olduğunu verir.

In [84]:
df.isnull().sum()

Movie_Title    0
YR_Released    0
Rating         0
Num_Reviews    0
Movie_ID       0
Record         0
Runtime        1
dtype: int64

**Ne yapar?**
- Her sütun için:
    - Kaç tane **NaN / eksik değer** olduğunu sayar

---

### Eksik Runtime Kaydını Bulma

Eğer sadece `Runtime` sütununda eksik veri varsa, hangi satır olduğunu görebiliriz.

In [85]:
missing_runtime = df[df["Runtime"].isnull()]
missing_runtime

  Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID             Record  Runtime
9    Álom.net         2009     1.9         8502  tt1309000  Bottom 250 Movies      NaN

---

## Eksik Veri İçin Temizleme Stratejileri

Eksik veri temizliği için 3 tip strateji vardır:

    1. Satır silmek: Veri kaybı olur ama en temiz yöntem olabilir.  
    2. Ortalama/medyan ile doldurmak: Veri kaybı olmaz ama dağılımı etkileyebilir.  
    3. Sabit değerle doldurmak: Genelde önerilmez (analizi bozar).

Bu veri setinde `Runtime` eksik sayısı **1** ise, çoğu senaryoda satırı silmek mantıklıdır.

---

### Satır Silme (Önerilen)

Sadece `Runtime` eksik olan satır(lar)ı siler.

In [ ]:
df_clean = df.dropna(subset=["Runtime"]).copy()
df_clean.shape

---

### Alternatif: Ortalama ile Doldurma (Opsiyonel)

Satır silmek istemiyorsan aşağıdaki yöntem kullanılabilir.
> Not: Bu yöntem `Runtime` dağılımını biraz yapaylaştırabilir.

In [ ]:
df_fill_mean = df.copy()
df_fill_mean["Runtime"] = df_fill_mean["Runtime"].fillna(df_fill_mean["Runtime"].mean())
df_fill_mean.isnull().sum()

---

## Basit İpuçları (EDA Notları)

- `df.sample(5)` → rastgele 5 satır görmek için iyi bir yöntem

In [86]:
df.sample(5)

                  Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID                 Record  Runtime
643        Back to the Future         1985     8.5       801488  tt0088763         Top 250 Movies    116.0
115                Goodfellas         1990     8.7       788904  tt0099685     Top 250 Eng Movies    146.0
474          The Ghazi Attack         2017     7.6         5250  tt6299040  Top 250 Indian Movies    116.0
61              The Skydivers         1963     2.5         4463  tt0057507      Bottom 250 Movies     75.0
425  Manjhi: The Mountain Man         2015     7.9        13425  tt3449292  Top 250 Indian Movies    120.0

- `df.nunique()` → her sütunda kaç farklı değer var?

In [88]:
df.nunique()

Movie_Title    653
YR_Released     88
Rating          38
Num_Reviews    645
Movie_ID       656
Record           4
Runtime        135
dtype: int64

- `df["col"].value_counts()` → kategorik dağılım

In [92]:
df["Movie_Title"].value_counts()

Drishyam                            3
The Treasure of the Sierra Madre    2
Unforgiven                          2
The Third Man                       2
Up                                  2
                                   ..
JFK                                 1
The Graduate                        1
A Christmas Story                   1
The King's Speech                   1
In the Mood for Love                1
Name: Movie_Title, Length: 653, dtype: int64


- `df.corr(numeric_only=True)` → sayısal korelasyon

In [90]:
df.corr(numeric_only=True)

             YR_Released    Rating  Num_Reviews   Runtime
YR_Released     1.000000 -0.102785     0.085856  0.221095
Rating         -0.102785  1.000000     0.382232  0.383230
Num_Reviews     0.085856  0.382232     1.000000  0.070265
Runtime         0.221095  0.383230     0.070265  1.000000

---

## `.loc` vs `.iloc`

> `.loc` **isimle (label),** `.iloc` **sıra numarasıyla (index) seçer.**


🔑 **Temel fark**

| Özellik       | `.loc`             | `.iloc`              |
| ------------- | ------------------ | -------------------- |
| Seçim türü    | **Label (etiket)** | **Index (pozisyon)** |
| Satır         | index adı          | 0-based sıra         |
| Sütun         | sütun adı          | sütun sırası         |
| Okunabilirlik | ⭐⭐⭐⭐⭐       | ⭐⭐⭐             |
| Hata riski    | Düşük              | Daha yüksek          |

---

### `.loc` → İsme göre seçim (Label-based)

In [93]:
df.loc[1, "Movie_Title"]

'Saving Christmas'

**Ne olur?**
- `1` → **index label**
- `"Movie_Title"` → sütun adı

📌 Yani:
> **Index’i 1 olan satırın Movie_Title değeri**

---

#### Sayısal sütun

In [94]:
df.loc[1, "Num_Reviews"]

12765

📌 Bu yüzden `.loc`:
- Okunur
- Güvenlidir
- Gerçek projelerde **tercih edilir**

---

### `.iloc` → Sıraya göre seçim (Position-based)
Aynı veriyi `iloc` ile alalım

In [114]:
df.iloc[1, 0]

'Saving Christmas'

**Ne olur?**
- `1` → 2. satır (0-based)
- `0` → 1. sütun

---


#### Num_Reviews

In [96]:
df.iloc[1, 3]

12765

⚠️ Problem:
- Sütun sırası değişirse kod **bozulur**
- Okunması zor

---

#### Karşılaştırma

| Amaç      | `.loc`                     | `.iloc`         |
| --------- | -------------------------- | --------------- |
| Film adı  | `df.loc[1, "Movie_Title"]` | `df.iloc[1, 0]` |
| Oy sayısı | `df.loc[1, "Num_Reviews"]` | `df.iloc[1, 3]` |

➡️ **Aynı sonuç**, farklı erişim yolu.

---

#### Satır / Sütun Aralıkları
##### `.loc`**(dahil)** ile aralık

In [130]:
df.loc[0:5, ["Movie_Title", "Rating"]]

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7
5                  Pledge This!     1.7

✔ 5 **dahil**

---

##### `.iloc`**(hariç)** ile aralık

In [131]:
df.iloc[0:5, 0:2]

                    Movie_Title  YR_Released
0             Code Name: K.O.Z.         2015
1              Saving Christmas         2014
2  Superbabies: Baby Geniuses 2         2004
3             Daniel the Wizard         2004
4      Manos: The Hands of Fate         1966

❌ 5 **dahil değil**

---

#### Filtreleme + .loc (EN ÖNEMLİ KISIM)

In [116]:
df.loc[df["Rating"] >= 8, ["Movie_Title", "Rating"]]

                                           Movie_Title  Rating
100                           The Shawshank Redemption     9.2
101                                      The Godfather     9.2
102                             The Godfather: Part II     9.0
103                                    The Dark Knight     9.0
104                                       12 Angry Men     8.9
..                                                 ...     ...
845  Pirates of the Caribbean: The Curse of the Bla...     8.0
846                   What Ever Happened to Baby Jane?     8.0
847                                       Paris, Texas     8.0
848                                           Drishyam     8.0
849                                                 PK     8.0

[573 rows x 2 columns]

📌 Bu kullanım:
- Profesyonel
- Okunaklı
- Temiz
- Güvenli
- Analitik

`.iloc` ile bu kadar okunaklı olmaz.

---

#### Ne Zaman Hangisi?
✅ `.loc` kullan:
- Sütun adını biliyorsan
- Filtreleme yapıyorsan
- Analiz / EDA yapıyorsan
- Notebook yazıyorsan

⚠️ `.iloc` kullan:
- Hızlı test
- Loop içinde pozisyon lazım
- Sütun sırası **sabit** ve **garanti** ise

---

🎯 **Altın Kural**
- %90 durumda `.loc` kullan
- `.iloc` → özel durum aracı (pozisyon gerçekten gerekiyorsa)

**Mini Cheat Sheet**

In [135]:
# Tek hücre
df.loc[1, "Movie_Title"]

'Saving Christmas'

In [132]:
# Birden fazla sütun
df.loc[1, ["Movie_Title", "Rating"]]

Movie_Title    Saving Christmas
Rating                      1.5
Name: 1, dtype: object

In [133]:
# Koşullu seçim
df.loc[df["Rating"] > 8, :]

                            Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID              Record  Runtime
100            The Shawshank Redemption         1994     9.2      1829037  tt0111161  Top 250 Eng Movies    142.0
101                       The Godfather         1972     9.2      1249333  tt0068646  Top 250 Eng Movies    175.0
102              The Godfather: Part II         1974     9.0       860228  tt0071562  Top 250 Eng Movies    202.0
103                     The Dark Knight         2008     9.0      1808543  tt0468569  Top 250 Eng Movies    152.0
104                        12 Angry Men         1957     8.9       497242  tt0050083  Top 250 Eng Movies     96.0
..                                  ...          ...     ...          ...        ...                 ...      ...
808                     The Truman Show         1998     8.1       727241  tt0120382      Top 250 Movies    103.0
809               The Nights of Cabiria         1957     8.1        29373  tt0050783      Top 250 Movies    110.0
810                  The Princess Bride         1987     8.1       316058  tt0093779      Top 250 Movies     98.0
811                 Hachi: A Dog's Tale         2009     8.1       180654  tt1028532      Top 250 Movies     93.0
812  Nausicaä of the Valley of the Wind         1984     8.1       106541  tt0087544      Top 250 Movies    117.0

[449 rows x 7 columns]

In [134]:
# iloc karşılığı
df.iloc[1, 0]

'Saving Christmas'

---

In [118]:
# Saving Christmas filminin Num of Reviews bilgisini yazdırınız
df.iloc[1, 3]

12765

**Neden çalışıyor?**
- `iloc` **pozisyon bazlıdır**
- `1` → 2. satır (index 1 → **Saving Christmas*)
- `3` → 4. sütun

Sütun sıralaması:
- 0 → Movie_Title
- 1 → YR_Released
- 2 → Rating
- 3 → Num_Reviews

Bu kod **çalışır ama kırılgandır.** (Sütun sırası değişirse sonuç yanlış olur.)

---

In [102]:
# 5 ile 10 satırlardaki filmlerin isimlerini ekrana yazdırın
df.loc[5:10, "Movie_Title"]

5                       Pledge This!
6      Dünyayi Kurtaran Adam'in Oglu
7                         Foodfight!
8         Birdemic: Shock and Terror
9                           Álom.net
10    Titanic - La leggenda continua
Name: Movie_Title, dtype: object

**Neden `.loc` kullandık?**
- `.loc` → **label-based**
- Index aralığı **dahil–dahil** çalışır

**Eğer `.iloc` kullansaydık?**

In [119]:
df.iloc[5:11, 0]

5                       Pledge This!
6      Dünyayi Kurtaran Adam'in Oglu
7                         Foodfight!
8         Birdemic: Shock and Terror
9                           Álom.net
10    Titanic - La leggenda continua
Name: Movie_Title, dtype: object

📌 Çünkü:
- iloc’ta **üst sınır hariçtir**

---

In [ ]:
# ilk 10 filmi ekrana yazdırınız
df.loc[:10, "Movie_Title"]

0                  Code Name: K.O.Z.
1                   Saving Christmas
2       Superbabies: Baby Geniuses 2
3                  Daniel the Wizard
4           Manos: The Hands of Fate
5                       Pledge This!
6      Dünyayi Kurtaran Adam'in Oglu
7                         Foodfight!
8         Birdemic: Shock and Terror
9                           Álom.net
10    Titanic - La leggenda continua
Name: Movie_Title, dtype: object

**Nasıl çalışır?**
- `.loc` → **label-based**
- `:10` → **0’dan 10’a kadar**
- `"Movie_Title"` → sadece film isimleri

📌 **Önemli nokta** (`.loc` kuralı):
> Üst sınır **DAHİL**

**`.iloc` (pozisyon bazlı, önerilen)**

In [120]:
df.iloc[:10, 0]

0                Code Name: K.O.Z.
1                 Saving Christmas
2     Superbabies: Baby Geniuses 2
3                Daniel the Wizard
4         Manos: The Hands of Fate
5                     Pledge This!
6    Dünyayi Kurtaran Adam'in Oglu
7                       Foodfight!
8       Birdemic: Shock and Terror
9                         Álom.net
Name: Movie_Title, dtype: object

In [123]:
df['Movie_Title'].head(10)

0                Code Name: K.O.Z.
1                 Saving Christmas
2     Superbabies: Baby Geniuses 2
3                Daniel the Wizard
4         Manos: The Hands of Fate
5                     Pledge This!
6    Dünyayi Kurtaran Adam'in Oglu
7                       Foodfight!
8       Birdemic: Shock and Terror
9                         Álom.net
Name: Movie_Title, dtype: object

---

In [104]:
# 10 ile 20 satırların Movie_Title, Num_Reviews
df.loc[10:20, ["Movie_Title", "Num_Reviews"]]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0
20     Attack of the Jurassic Shark            0

**Nasıl çalışır?**
- `10:20` → 10, 11, 12, …, 20 (20 dahil)
- `["Movie_Title", "Num_Reviews"]` → iki sütun birlikte

📌 Çıktı doğru çünkü:
- `.loc` aralıkları **inclusive**
- Sütunlar **isimle** seçildi → güvenli

**Eğer `.iloc` ile yazılsaydı:**

In [121]:
df.iloc[10:21, [0, 3]]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0
20     Attack of the Jurassic Shark            0

Ama:
- Okunması zor
- Sütun sırası değişirse bozulur ❌

---

- **Analiz yazıyorsan** `.loc`, **indeks hesabı yapıyorsan** `.iloc.`
- `.loc` **okunabilirlik**, `.iloc` **kontrollü dilimleme** içindir.

---

#### Tek Sütun Seçimi

In [105]:
df['Movie_Title']

0                                      Code Name: K.O.Z.
1                                       Saving Christmas
2                           Superbabies: Baby Geniuses 2
3                                      Daniel the Wizard
4                               Manos: The Hands of Fate
                             ...
845    Pirates of the Caribbean: The Curse of the Bla...
846                     What Ever Happened to Baby Jane?
847                                         Paris, Texas
848                                             Drishyam
849                                                   PK
Name: Movie_Title, Length: 850, dtype: object

**Tek köşeli parantez** - `Series`
- Veri tipi → `dtype: object`(string)

**Tek bir sütunu** döndürür
- Movie_Title sütununu seçer

Dönen veri tipi: Series

📌 Özellikler:
- Tek boyutludur
- Index + değer içerir
- Filtreleme ve string işlemleri için uygundur

**`.loc` — Label (Etiket) Bazlı Seçim**

In [122]:
df.loc[:, 'Movie_Title']

0                                      Code Name: K.O.Z.
1                                       Saving Christmas
2                           Superbabies: Baby Geniuses 2
3                                      Daniel the Wizard
4                               Manos: The Hands of Fate
                             ...
845    Pirates of the Caribbean: The Curse of the Bla...
846                     What Ever Happened to Baby Jane?
847                                         Paris, Texas
848                                             Drishyam
849                                                   PK
Name: Movie_Title, Length: 850, dtype: object

Ama `.loc`:
- filtreleme
- çoklu sütun
- güncelleme
için **daha güçlüdür.**

---

#### DataFrame olarak almak

In [106]:
df[['Movie_Title']]

                                           Movie_Title
0                                    Code Name: K.O.Z.
1                                     Saving Christmas
2                         Superbabies: Baby Geniuses 2
3                                    Daniel the Wizard
4                             Manos: The Hands of Fate
..                                                 ...
845  Pirates of the Caribbean: The Curse of the Bla...
846                   What Ever Happened to Baby Jane?
847                                       Paris, Texas
848                                           Drishyam
849                                                 PK

[850 rows x 1 columns]

➡️ DataFrame

📌 Fark:
- Çift köşeli parantez → DataFrame → tablo (satır + sütun)
- Tek köşeli parantez → Series → tek boyut

---

In [124]:
df[
    ['Movie_Title', 'Num_Reviews']
][10:20]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0

**Nasıl çalışır?**
- Satır → index label
- Sütun → sütun adı
- Aralıklar DAHİL–DAHİL

- **Yeni bir DataFrame** oluşturur (sadece bu 2 sütun)
- Bu **yeni DataFrame üzerinde** satır dilimlemesi yapar

Sorunları:
- Okunabilirlik düşüktür
- `SettingWithCopyWarning` risklidir
- Güncelleme (=) yaparken **sessiz hatalara** yol açar
- pandas dokümantasyonunda önerilmez

**`.loc` — Label (Etiket) Bazlı Seçim**

In [107]:
df.loc[10:20, ['Movie_Title', 'Num_Reviews']]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0
20     Attack of the Jurassic Shark            0

**Nasıl çalışır?**
- Satır → **index label**
- Sütun → **sütun adı**
- Aralıklar **DAHİL–DAHİL**

📌 Bu kullanım:
- Tek adımda seçim
- Hem satır hem sütun **aynı anda**
- Okunaklı
- Güvenli
- pandas tarafından önerilen ve gerçek projelerde ki standart yöntem

**`.iloc` — Pozisyon Bazlı Seçim**

In [108]:
df.iloc[10:20, [0, 3]]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0

**Nasıl çalışır?**
- Satır → **0-based pozisyon**
- Sütun → **0-based pozisyon**
- Üst sınır **hariçtir**

📌 Dezavantaj:
- Sütun sırası değişirse kod bozulur
- Okunabilirliği düşüktür

**Yanlış Ama Çalışan Kullanım (Chained Indexing)**

In [109]:
df[['Movie_Title', 'Num_Reviews']][10:20]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0

**Neden yanlış?**

Bu kullanım:
- Önce **sütun** seçer
- Sonra **satır** seçer

Bu yapıya **Chained Indexing** denir.

📌 Sorunları:
- `SettingWithCopyWarning` üretir
- Güncelleme yaparken veri kaybına yol açabilir
- pandas dokümantasyonunda **önerilmez**

**Doğru ve Profesyonel Kullanım**

✅ Doğru Karşılığı

In [110]:
df.loc[10:20, ['Movie_Title', 'Num_Reviews']]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0
20     Attack of the Jurassic Shark            0

**Neden doğru?**
- Tek adımda seçim
- Hem satır hem sütun aynı anda
- Güncellemeler güvenlidir

**Dilimleme Farkları (Çok Önemli)**
| Kod              | Açıklama         |
| ---------------- | ---------------- |
| `df[10:20]`      | 10–19 (20 hariç) |
| `df.loc[10:20]`  | 10–20 (20 dahil) |
| `df.iloc[10:20]` | 10–19            |

**Güncelleme Senaryosu (Tehlikeli Örnek)**

In [111]:
df[['Movie_Title','Num_Reviews']][10:20]['Num_Reviews'] = 0

❌ Bu kod:
- Sessizce başarısız olabilir
- pandas uyarı verir
- Gerçek projelerde **kritik hatadır**

✅ Doğru Güncelleme

In [112]:
df.loc[10:20, 'Num_Reviews'] = 0

**Özet — Altın Kurallar**

✅ Yapılması Gerekenler
- Satır + sütun → `.loc`
- Pozisyon gerekiyorsa → `.iloc`
- Güncelleme → **mutlaka** `.loc`

❌ Kaçınılması Gerekenler
- `df[...][...]`
- Sütun numarasıyla erişim
- Güncellemede chained indexing

---

##### Mini Cheat Sheet

In [136]:
# Tek sütun
df['Movie_Title']

0                                      Code Name: K.O.Z.
1                                       Saving Christmas
2                           Superbabies: Baby Geniuses 2
3                                      Daniel the Wizard
4                               Manos: The Hands of Fate
                             ...
845    Pirates of the Caribbean: The Curse of the Bla...
846                     What Ever Happened to Baby Jane?
847                                         Paris, Texas
848                                             Drishyam
849                                                   PK
Name: Movie_Title, Length: 850, dtype: object

In [127]:
# Birden fazla sütun
df[['Movie_Title', 'Num_Reviews']]

                                           Movie_Title  Num_Reviews
0                                    Code Name: K.O.Z.        24623
1                                     Saving Christmas        12765
2                         Superbabies: Baby Geniuses 2        26505
3                                    Daniel the Wizard        13295
4                             Manos: The Hands of Fate        31808
..                                                 ...          ...
845  Pirates of the Caribbean: The Curse of the Bla...       872441
846                   What Ever Happened to Baby Jane?        37906
847                                       Paris, Texas        55587
848                                           Drishyam        40777
849                                                 PK       106375

[850 rows x 2 columns]

In [128]:
# Satır + sütun (önerilen)
df.loc[10:20, ['Movie_Title', 'Num_Reviews']]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0
20     Attack of the Jurassic Shark            0

In [129]:
# Pozisyon bazlı
df.iloc[10:20, [0, 3]]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua            0
11                   Disaster Movie            0
12                    Zombie Nation            0
13          The Hottie & the Nottie            0
14       Keloglan Karaprens'e Karsi            0
15             From Justin to Kelly            0
16                     A Fox's Tale            0
17  Ram Gopal Varma's Indian Flames            0
18                  Going Overboard            0
19         Emret Komutanim: Sah Mat            0

In [ ]:
# Path - log
# loc → label-based (etiket bazlı) seçim yapar
df.loc[:, ['Movie_Title', 'Rating', 'Num_Reviews']]

                                           Movie_Title  Rating  Num_Reviews
0                                    Code Name: K.O.Z.     1.4        24623
1                                     Saving Christmas     1.5        12765
2                         Superbabies: Baby Geniuses 2     1.6        26505
3                                    Daniel the Wizard     1.6        13295
4                             Manos: The Hands of Fate     1.7        31808
..                                                 ...     ...          ...
845  Pirates of the Caribbean: The Curse of the Bla...     8.0       872441
846                   What Ever Happened to Baby Jane?     8.0        37906
847                                       Paris, Texas     8.0        55587
848                                           Drishyam     8.0        40777
849                                                 PK     8.0       106375

[850 rows x 3 columns]

**Açıklama:**
- `:` → **tüm satırlar**
- Liste → sadece seçilen kolonlar
  - `['Movie_Title', 'Rating', 'Num_Reviews']` → **sadece seçilen kolonlar**

👉 Yani: **“Tüm satırları al, ama sadece bu 3 kolonu göster.”**

In [7]:
# Path - ilog
df.iloc[:, [0, 1, 2]]

                                           Movie_Title  YR_Released  Rating
0                                    Code Name: K.O.Z.         2015     1.4
1                                     Saving Christmas         2014     1.5
2                         Superbabies: Baby Geniuses 2         2004     1.6
3                                    Daniel the Wizard         2004     1.6
4                             Manos: The Hands of Fate         1966     1.7
..                                                 ...          ...     ...
845  Pirates of the Caribbean: The Curse of the Bla...         2003     8.0
846                   What Ever Happened to Baby Jane?         1962     8.0
847                                       Paris, Texas         1984     8.0
848                                           Drishyam         2015     8.0
849                                                 PK         2014     8.0

[850 rows x 3 columns]

In [8]:
df[['Movie_Title', 'Rating', 'Num_Reviews']]

                                           Movie_Title  Rating  Num_Reviews
0                                    Code Name: K.O.Z.     1.4        24623
1                                     Saving Christmas     1.5        12765
2                         Superbabies: Baby Geniuses 2     1.6        26505
3                                    Daniel the Wizard     1.6        13295
4                             Manos: The Hands of Fate     1.7        31808
..                                                 ...     ...          ...
845  Pirates of the Caribbean: The Curse of the Bla...     8.0       872441
846                   What Ever Happened to Baby Jane?     8.0        37906
847                                       Paris, Texas     8.0        55587
848                                           Drishyam     8.0        40777
849                                                 PK     8.0       106375

[850 rows x 3 columns]

**Amaç:** 1. ve 7. satırların `Movie_Title` ve `Rating` bilgilerini almak.

#### ✅ `iloc` (index bazlı)
- Satır ve kolonlar **numara** ile seçilir
- Indexler **0'dan başlar**

In [12]:
df.iloc[[1, 7], [0, 2]]

        Movie_Title  Rating
1  Saving Christmas     1.5
7        Foodfight!     1.8

#### ✅ `loc` (isim bazlı)
- Satırlar **index etiketi**, kolonlar **isim** ile seçilir
- Okunabilirlik daha yüksektir

In [10]:
df.loc[[1, 7], ['Movie_Title', 'Rating']]

        Movie_Title  Rating
1  Saving Christmas     1.5
7        Foodfight!     1.8

In [13]:
df[['Movie_Title', 'Rating', 'Num_Reviews']]

                                           Movie_Title  Rating  Num_Reviews
0                                    Code Name: K.O.Z.     1.4        24623
1                                     Saving Christmas     1.5        12765
2                         Superbabies: Baby Geniuses 2     1.6        26505
3                                    Daniel the Wizard     1.6        13295
4                             Manos: The Hands of Fate     1.7        31808
..                                                 ...     ...          ...
845  Pirates of the Caribbean: The Curse of the Bla...     8.0       872441
846                   What Ever Happened to Baby Jane?     8.0        37906
847                                       Paris, Texas     8.0        55587
848                                           Drishyam     8.0        40777
849                                                 PK     8.0       106375

[850 rows x 3 columns]

- Tek sütun = Series, 
- çok sütun = DataFrame

🎯 Sonuç
> pandas’ta **doğru indexleme**, **hatasız analiz + güvenli güncelleme** demektir.

**Amaç:** `Movie_Title` ve `Rating` sütunlarının ilk beş satırının bilgilerini almak.

In [14]:
df[['Movie_Title', 'Rating']].head()

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7

In [16]:
df[['Movie_Title', 'Rating']][:5]

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7

In [17]:
df.loc[:, ['Movie_Title', 'Rating']].head()

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7

In [18]:
df.loc[:, ['Movie_Title', 'Rating']][:5]

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7

In [19]:
df.iloc[:5, [0, 2]]

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7

## Data Filtering

### 🎯 `query` ile Filtreleme

2000 yılından sonra çıkan filmleri getirelim.

In [20]:
(
    df.query('YR_Released > 2000')
)

                                           Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID             Record  Runtime
0                                    Code Name: K.O.Z.         2015     1.4        24623  tt4458206  Bottom 250 Movies    114.0
1                                     Saving Christmas         2014     1.5        12765  tt4009460  Bottom 250 Movies     80.0
2                         Superbabies: Baby Geniuses 2         2004     1.6        26505  tt0270846  Bottom 250 Movies     88.0
3                                    Daniel the Wizard         2004     1.6        13295  tt0421051  Bottom 250 Movies     81.0
5                                         Pledge This!         2006     1.7        15836  tt0417056  Bottom 250 Movies     91.0
..                                                 ...          ...     ...          ...        ...                ...      ...
839                                 Gangs of Wasseypur         2012     8.0        54250  tt1954470     Top 250 Movies    320.0
840                                           The Help         2011     8.0       345567  tt1454029     Top 250 Movies    146.0
845  Pirates of the Caribbean: The Curse of the Bla...         2003     8.0       872441  tt0325980     Top 250 Movies    143.0
848                                           Drishyam         2015     8.0        40777  tt4430212     Top 250 Movies    163.0
849                                                 PK         2014     8.0       106375  tt2338151     Top 250 Movies    153.0

[405 rows x 7 columns]

#### 🧠 Açıklama
- `YR_Released` → kolon adı
- `>` → büyüktür
- `2000` → karşılaştırılan değer

Yani: **2000’den sonra çıkan filmler**

### 🔍 Filtre + Kolon Seçimi

In [24]:
(
    df.query('YR_Released > 2000')
        .loc[:, ['Movie_Title', 'Rating']]
)

                                           Movie_Title  Rating
0                                    Code Name: K.O.Z.     1.4
1                                     Saving Christmas     1.5
2                         Superbabies: Baby Geniuses 2     1.6
3                                    Daniel the Wizard     1.6
5                                         Pledge This!     1.7
..                                                 ...     ...
839                                 Gangs of Wasseypur     8.0
840                                           The Help     8.0
845  Pirates of the Caribbean: The Curse of the Bla...     8.0
848                                           Drishyam     8.0
849                                                 PK     8.0

[405 rows x 2 columns]

### 🎯 Boolean Indexing
Boolean indexing, DataFrame içindeki satırları **True / False** koşullarına göre
filtrelememizi sağlar.

#### 1️⃣ Koşul Oluşturma

In [21]:
df['YR_Released'] > 2000

0       True
1       True
2       True
3       True
4      False
       ...
845     True
846    False
847    False
848     True
849     True
Name: YR_Released, Length: 850, dtype: bool

Yukarıdaki ifade her satır için **True / False** üretir.

#### 2️⃣ Koşulu DataFrame’e Uygulama

In [22]:
df[
    df['YR_Released'] > 2000
]

                                           Movie_Title  YR_Released  Rating  Num_Reviews   Movie_ID             Record  Runtime
0                                    Code Name: K.O.Z.         2015     1.4        24623  tt4458206  Bottom 250 Movies    114.0
1                                     Saving Christmas         2014     1.5        12765  tt4009460  Bottom 250 Movies     80.0
2                         Superbabies: Baby Geniuses 2         2004     1.6        26505  tt0270846  Bottom 250 Movies     88.0
3                                    Daniel the Wizard         2004     1.6        13295  tt0421051  Bottom 250 Movies     81.0
5                                         Pledge This!         2006     1.7        15836  tt0417056  Bottom 250 Movies     91.0
..                                                 ...          ...     ...          ...        ...                ...      ...
839                                 Gangs of Wasseypur         2012     8.0        54250  tt1954470     Top 250 Movies    320.0
840                                           The Help         2011     8.0       345567  tt1454029     Top 250 Movies    146.0
845  Pirates of the Caribbean: The Curse of the Bla...         2003     8.0       872441  tt0325980     Top 250 Movies    143.0
848                                           Drishyam         2015     8.0        40777  tt4430212     Top 250 Movies    163.0
849                                                 PK         2014     8.0       106375  tt2338151     Top 250 Movies    153.0

[405 rows x 7 columns]

Bu kodun anlamı:

> **YR_Released > 2000 olan satırları getir**

### `sort_values()` Nedir?

`sort_values()` bir **DataFrame veya Series** içindeki verileri
belirtilen değerlere göre sıralamak için kullanılır.

- Varsayılan olarak **küçükten büyüğe** sıralar.

In [25]:
(
    df.query('YR_Released > 2000')
      .loc[:, ['Movie_Title', 'YR_Released', 'Rating']]
      .sort_values(by='Rating', ascending=False)
)

                                           Movie_Title  YR_Released  Rating
603                                    The Dark Knight         2008     9.0
103                                    The Dark Knight         2008     9.0
607      The Lord of the Rings: The Return of the King         2003     8.9
106      The Lord of the Rings: The Return of the King         2003     8.9
610  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
..                                                 ...          ...     ...
5                                         Pledge This!         2006     1.7
2                         Superbabies: Baby Geniuses 2         2004     1.6
3                                    Daniel the Wizard         2004     1.6
1                                     Saving Christmas         2014     1.5
0                                    Code Name: K.O.Z.         2015     1.4

[405 rows x 3 columns]

In [ ]:
# 2000'den sonra yayınlanmış rating en çok olan top 10 movie
(
    df.query('YR_Released > 2000')
        .loc[:, ['Movie_Title', 'YR_Released', 'Rating']]
        .sort_values(by='Rating', ascending=False)
        .head(10)
)

                                           Movie_Title  YR_Released  Rating
603                                    The Dark Knight         2008     9.0
103                                    The Dark Knight         2008     9.0
607      The Lord of the Rings: The Return of the King         2003     8.9
106      The Lord of the Rings: The Return of the King         2003     8.9
610  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
109  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
614              The Lord of the Rings: The Two Towers         2002     8.7
613                                          Inception         2010     8.7
113              The Lord of the Rings: The Two Towers         2002     8.7
112                                          Inception         2010     8.7

In [29]:
(
    df[df['YR_Released'] > 2000]
      .loc[:, ['Movie_Title', 'YR_Released', 'Rating']]
      .sort_values(by='Rating', ascending=False)
      .head(10)
)

                                           Movie_Title  YR_Released  Rating
603                                    The Dark Knight         2008     9.0
103                                    The Dark Knight         2008     9.0
607      The Lord of the Rings: The Return of the King         2003     8.9
106      The Lord of the Rings: The Return of the King         2003     8.9
610  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
109  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
614              The Lord of the Rings: The Two Towers         2002     8.7
613                                          Inception         2010     8.7
113              The Lord of the Rings: The Two Towers         2002     8.7
112                                          Inception         2010     8.7

In [28]:
(
    df[df['YR_Released'] > 2000]
      [['Movie_Title', 'YR_Released', 'Rating']]
      .sort_values(by='Rating', ascending=False)
      .head(10)
)

                                           Movie_Title  YR_Released  Rating
603                                    The Dark Knight         2008     9.0
103                                    The Dark Knight         2008     9.0
607      The Lord of the Rings: The Return of the King         2003     8.9
106      The Lord of the Rings: The Return of the King         2003     8.9
610  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
109  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
614              The Lord of the Rings: The Two Towers         2002     8.7
613                                          Inception         2010     8.7
113              The Lord of the Rings: The Two Towers         2002     8.7
112                                          Inception         2010     8.7

In [30]:
(
    df[
        (df['Rating'] > 7.0) & (df['Rating'] < 9.0) 
    ][['Movie_Title', 'Rating', 'Num_Reviews']]
    .sort_values(by='Rating', ascending=False)
)

                                       Movie_Title  Rating  Num_Reviews
104                                   12 Angry Men     8.9       497242
604                                   12 Angry Men     8.9       497242
606                                   Pulp Fiction     8.9      1432193
607  The Lord of the Rings: The Return of the King     8.9      1311271
105                               Schindler's List     8.9       939136
..                                             ...     ...          ...
563                                 Gabbar is Back     7.1        18122
562                           Gadar: Ek Prem Katha     7.1         7257
561                                Bajirao Mastani     7.1        22453
560                                   Dedh Ishqiya     7.1         5751
582                                      Tere Naam     7.1        12333

[728 rows x 3 columns]

In [31]:
(
    df.loc[
        (df['Rating'] > 7.0) & (df['Rating'] < 9.0),
        ['Movie_Title', 'Rating', 'Num_Reviews']
    ]
    .sort_values(by='Rating', ascending=False)
)

                                       Movie_Title  Rating  Num_Reviews
104                                   12 Angry Men     8.9       497242
604                                   12 Angry Men     8.9       497242
606                                   Pulp Fiction     8.9      1432193
607  The Lord of the Rings: The Return of the King     8.9      1311271
105                               Schindler's List     8.9       939136
..                                             ...     ...          ...
563                                 Gabbar is Back     7.1        18122
562                           Gadar: Ek Prem Katha     7.1         7257
561                                Bajirao Mastani     7.1        22453
560                                   Dedh Ishqiya     7.1         5751
582                                      Tere Naam     7.1        12333

[728 rows x 3 columns]

In [8]:
(
    df.query('YR_Released > 2000 & Rating < 9.0')
        [['Movie_Title', 'YR_Released', 'Rating']]
        .sort_values(by='Rating', ascending=False)
)

                                           Movie_Title  YR_Released  Rating
607      The Lord of the Rings: The Return of the King         2003     8.9
106      The Lord of the Rings: The Return of the King         2003     8.9
610  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
109  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
614              The Lord of the Rings: The Two Towers         2002     8.7
..                                                 ...          ...     ...
5                                         Pledge This!         2006     1.7
3                                    Daniel the Wizard         2004     1.6
2                         Superbabies: Baby Geniuses 2         2004     1.6
1                                     Saving Christmas         2014     1.5
0                                    Code Name: K.O.Z.         2015     1.4

[403 rows x 3 columns]

**2000 ile 3000 arasında Num Reviews** değerine sahip filmleri filtreler, istenen kolonları seçer ve **Num Reviews** değerine göre azalan şekilde sıralar.

In [ ]:
(
    df.query('2000 < Num_Reviews < 3000')
      .loc[:, ['Movie_Title', 'Rating', 'Num_Reviews']]
      .sort_values(by='Num_Reviews', ascending=False)
)

                                 Movie_Title  Rating  Num_Reviews
20              Attack of the Jurassic Shark     2.0         2983
48                                 The Class     2.4         2968
23                   La leggenda del Titanic     2.0         2883
79           Dis - en historie om kjærlighet     2.7         2875
78  Boggy Creek II: And the Legend Continues     2.7         2838
45                             Final Justice     2.4         2792
91                              Time Chasers     2.7         2756
92                                Devil Fish     2.7         2624
77                          Zombie Nightmare     2.7         2593
66                      The Maize: The Movie     2.5         2540
71                           Prince of Space     2.6         2531
95                       I Accuse My Parents     2.7         2444
67                        The Touch of Satan     2.6         2442
97                     Stjerner uden hjerner     2.8         2332
58               Invasion of the Neptune Men     2.5         2246
99                 Warrior of the Lost World     2.8         2151
98                        Ghosts Can't Do It     2.8         2074

#### Açıklama
- `query`: Sayısal aralık filtresi
- `loc`: İstenen kolonları seçmek için
- `sort_values`: Yorum sayısına göre sıralama

`Movie_Title` içinde **King** geçen ve `Rating >= 7.0` olan filmleri filtreleyerek sonuçtan `Movie_Title`, `Rating`, `Num Reviews` kolonlarını seçip `Rating` değerine göre **azalan** (çoktan aza) sıralamak

In [ ]:
(
    df.query('Movie_Title.str.contains("King", case=False, na=False) & Rating >= 7.0')
    .loc[:, ['Movie_Title', 'Rating', 'Num_Reviews']]
    .sort_values(by='Rating', ascending=False)
)

                                       Movie_Title  Rating  Num_Reviews
106  The Lord of the Rings: The Return of the King     8.9      1311271
607  The Lord of the Rings: The Return of the King     8.9      1311271
139                                  The Lion King     8.5       708441
648                                  The Lion King     8.5       708441
168                          To Kill a Mockingbird     8.3       234667
686                          To Kill a Mockingbird     8.3       234667
209            Lock, Stock and Two Smoking Barrels     8.2       443715
743            Lock, Stock and Two Smoking Barrels     8.2       443715
329                              The King's Speech     8.0       538099

Parametreler:
- `case=False`: büyük/küçük harf duyarsız arama
- `na=False`: `Movie_Title` içinde `NaN/None` varsa hata vermesin

In [27]:
df[
    df["Movie_Title"].str.contains("King", case=False, na=False) & (df["Rating"] > 7.0)
].loc[:, ["Movie_Title", "Rating", "Num_Reviews"]].sort_values(by="Rating", ascending=False)

                                       Movie_Title  Rating  Num_Reviews
106  The Lord of the Rings: The Return of the King     8.9      1311271
607  The Lord of the Rings: The Return of the King     8.9      1311271
139                                  The Lion King     8.5       708441
648                                  The Lion King     8.5       708441
168                          To Kill a Mockingbird     8.3       234667
686                          To Kill a Mockingbird     8.3       234667
209            Lock, Stock and Two Smoking Barrels     8.2       443715
743            Lock, Stock and Two Smoking Barrels     8.2       443715
329                              The King's Speech     8.0       538099

## GroupBy()

Veri seti içerisinde bulunan spesifik bilgilere göre veri seti grouplamaya yarar.

In [26]:
df.groupby('YR_Released')['Num_Reviews'].sum().sort_values(ascending=False)

YR_Released
1994    12360599
1999    10961782
1995    10012874
2003     8759224
2010     8043754
          ...
1945       55125
1930       49233
1928       29550
1935       26078
1947       25158
Name: Num_Reviews, Length: 88, dtype: int64

- Tip: **Series**
- Index: `YR_Released`
- Değer: `Num_Reviews` toplamı

Bunu DataFrame'e çevirmek istersen:
```python
df.groupby('YR_Released')['Num_Reviews'].sum().reset_index()
```

In [16]:
(
    df.groupby('YR_Released')
      .agg({'Num_Reviews': 'sum'})
)

             Num_Reviews
YR_Released
1921              153844
1925              148998
1926              117028
1927              154896
1928               29550
...                  ...
2013             4719940
2014             7355387
2015             6110114
2016             2532549
2017             1089260

[88 rows x 1 columns]

- Tip: **DataFrame**
- Kolon adı korunur: `Num_Reviews`

İstersen index'i kolona çevirebilirsin:
```python
df.groupby('YR_Released', as_index=False).agg({'Num_Reviews': 'sum'})
```

## Ne zaman hangisi?

| İhtiyaç | Önerilen |
|---|---|
| Tek kolon, hızlı analiz | Path I |
| Birden fazla metrik/kolon | Path II (`agg`) |
| DataFrame çıktısı lazım | Path II |
| Çizim/grafik için hızlı seri | Path I |

### Bonus — Temiz isimlendirme + sıralama

En çok kullanılan modern stil:
- `as_index=False` (çıktı DataFrame ve `YR_Released` kolonda)
- Named aggregation ile yeni kolon adı
- Çoktan aza sıralama

In [17]:
(
    df.groupby('YR_Released', as_index=False)
      .agg(Num_Reviews_Total=('Num_Reviews', 'sum'))
      .sort_values('Num_Reviews_Total', ascending=False)
)

    YR_Released  Num_Reviews_Total
64         1994           12360599
69         1999           10961782
65         1995           10012874
73         2003            8759224
80         2010            8043754
..          ...                ...
15         1945              55125
5          1930              49233
4          1928              29550
8          1935              26078
17         1947              25158

[88 rows x 2 columns]

In [18]:
(
    df.groupby('YR_Released', as_index=False)
      .agg(Num_Reviews=('Num_Reviews', 'sum'))
      .query('700000 < Num_Reviews < 1000000')
      .sort_values(by='Num_Reviews', ascending=False)
)

    YR_Released  Num_Reviews
12         1941       884368
16         1946       837492
13         1942       834792
43         1973       782956
36         1966       781098
34         1964       753232
28         1958       740392
11         1940       726407

Filmleri `YR_Released` sütununa göre gruplayarak, her yıl için ortalama `Rating` değerini hesaplayıp ortalama Rating değeri 5.0 ile 10.0 arasında olan yılları filtreleyiniz. Sonucu ortalama Rating değerine göre çoktan aza sıralayınız.

In [20]:
(
    df.groupby('YR_Released', as_index=False)
      .agg(Avg_Rating=('Rating', 'mean'))
      .query('5.0 < Avg_Rating < 10.0')
      .sort_values('Avg_Rating', ascending=False)
)

    YR_Released  Avg_Rating
42         1972    8.800000
13         1942    8.500000
9          1936    8.500000
6          1931    8.466667
51         1981    8.433333
..          ...         ...
41         1971    6.416667
31         1961    6.216667
59         1989    6.116667
36         1966    5.912500
35         1965    5.200000

[87 rows x 2 columns]

In [ ]:
(
    df.sort_values(by='Rating', ascending=False)
      [['Movie_Title', 'Rating']]
)

                      Movie_Title  Rating
601                 The Godfather     9.2
600      The Shawshank Redemption     9.2
100      The Shawshank Redemption     9.2
101                 The Godfather     9.2
603               The Dark Knight     9.0
..                            ...     ...
4        Manos: The Hands of Fate     1.7
3               Daniel the Wizard     1.6
2    Superbabies: Baby Geniuses 2     1.6
1                Saving Christmas     1.5
0               Code Name: K.O.Z.     1.4

[850 rows x 2 columns]

🧠 Altın kural

> ❝ `groupby` → `agg` → filtre yapacaksan
> 
> index mi kolon mu olduğunu mutlaka kontrol et ❞