# Pandas Merge (Join)

Bu notebook pandas `merge` konusunu örneklerle açıklar.

In [1]:
import pandas as pd

## Örnek Veri

In [2]:
customers = {
    'customer_id': [1, 2, 3],
    'full_name': ['Burak Yılmaz', 'Hakan Yılmaz', 'İpek Yılmaz'],
    'address': ['Ataköy', 'Sarıyer', 'Sarıyer']
}

orders = {
    'order_id': [1001, 1002, 1003, 1004, 1005],
    'customer_id': [1, 2, 3, 4, 5],
    'order_revenue': [2456, 1234, 4567, 2345, 9876]
}

df_customers = pd.DataFrame(customers)
df_orders = pd.DataFrame(orders)

In [8]:
df_customers

   customer_id     full_name  address
0            1  Burak Yılmaz   Ataköy
1            2  Hakan Yılmaz  Sarıyer
2            3   İpek Yılmaz  Sarıyer

In [9]:
df_orders

   order_id  customer_id  order_revenue
0      1001            1           2456
1      1002            2           1234
2      1003            3           4567
3      1004            4           2345
4      1005            5           9876

## Merge

`merge`, iki veya daha fazla **DataFrame’i ortak bir anahtar (key)** üzerinden birleştirmeye yarar.
> SQL’deki `JOIN` işlemlerinin pandas karşılığıdır.

```python
pd.merge(left_df, right_df, on='key')
```

---

### 🔑 Temel Parametreler

| Parametre  | Açıklama                     |
| ---------- | ---------------------------- |
| `left`     | Sol DataFrame                |
| `right`    | Sağ DataFrame                |
| `on`       | Ortak kolon adı              |
| `how`      | Birleştirme türü             |
| `left_on`  | Sol DF kolon adı             |
| `right_on` | Sağ DF kolon adı             |
| `suffixes` | Aynı isimli kolonlar için ek |

---

### 🔗 Merge Türleri (how)

#### 1️⃣ Inner Merge (varsayılan)

**Inner merge**, iki DataFrame’i **ortak bir anahtar kolona göre** birleştirir ve
**SADECE her iki tabloda da bulunan ortak kayıtları** döndürür.

> Ortak olmayan kayıtlar **tamamen elenir.**

📌 **Kural**

> **Sol tabloda VAR + Sağ tabloda VAR → GELİR**
>
> **Biri yoksa → GELMEZ**

In [10]:
# inner merge
inner_merge = pd.merge(
    left=df_customers,
    right=df_orders,
    on='customer_id',
    how='inner'
)

inner_merge

   customer_id     full_name  address  order_id  order_revenue
0            1  Burak Yılmaz   Ataköy      1001           2456
1            2  Hakan Yılmaz  Sarıyer      1002           1234
2            3   İpek Yılmaz  Sarıyer      1003           4567

📌 Not:
- `how` parametresi yazılmadığında **varsayılan** = `inner`’dır.
- Yani bu kod zaten **inner join** yapar.

#### Left Merge

- **Ana tablo** (sol tablo)
- Çıktıdaki **satır sayısını belirleyen** tablo

In [3]:
left_merge = pd.merge(
    left=df_orders,
    right=df_customers,
    on='customer_id',
    how='left'
)

left_merge

   order_id  customer_id  order_revenue     full_name  address
0      1001            1           2456  Burak Yılmaz   Ataköy
1      1002            2           1234  Hakan Yılmaz  Sarıyer
2      1003            3           4567   İpek Yılmaz  Sarıyer
3      1004            4           2345           NaN      NaN
4      1005            5           9876           NaN      NaN

LEFT JOIN mantığı:

- Sol tablodaki (df_orders) **tüm satırlar korunur**
- Sağ tabloda eşleşme yoksa → `NaN`

#### Right Merge

In [4]:
right_merge = pd.merge(
    left=df_customers,
    right=df_orders,
    on='customer_id',
    how='right'
)

right_merge

   customer_id     full_name  address  order_id  order_revenue
0            1  Burak Yılmaz   Ataköy      1001           2456
1            2  Hakan Yılmaz  Sarıyer      1002           1234
2            3   İpek Yılmaz  Sarıyer      1003           4567
3            4           NaN      NaN      1004           2345
4            5           NaN      NaN      1005           9876