# Auto Dataset — Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    filepath_or_buffer='data/auto.csv'
)

df.head()

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [9]:
df.columns = ["symboling", "normalized-losses", "make", "fuel-type", "aspiration", "num-of-doors", "body-style",
              "drive-wheels", "engine-location", "wheel-base", "length", "width", "height", "curb-weight",
              "engine-type", "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio",
              "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "price"]

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [26]:
df.replace(
    to_replace='?',
    value=np.nan,
    inplace=True
) 

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [17]:
df.isna().sum() # Check for missing values in each column

symboling             0
normalized-losses    40
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
missing_values_df = df.isnull() # Create a DataFrame indicating missing values

missing_values_df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
for column_name in missing_values_df.columns.tolist():
    print(
        '============================\n'
        f'Column Name: {column_name}\n'
        f'Missing Values Count: {missing_values_df[column_name].value_counts()}'
    )

============================
Column Name: symboling
Missing Values Count: False    204
Name: symboling, dtype: int64
============================
Column Name: normalized-losses
Missing Values Count: False    164
True      40
Name: normalized-losses, dtype: int64
============================
Column Name: make
Missing Values Count: False    204
Name: make, dtype: int64
============================
Column Name: fuel-type
Missing Values Count: False    204
Name: fuel-type, dtype: int64
============================
Column Name: aspiration
Missing Values Count: False    204
Name: aspiration, dtype: int64
============================
Column Name: num-of-doors
Missing Values Count: False    202
True       2
Name: num-of-doors, dtype: int64
============================
Column Name: body-style
Missing Values Count: False    204
Name: body-style, dtype: int64
============================
Column Name: drive-wheels
Missing Values Count: False    204
Name: drive-wheels, dtype: int64
============================
Column Name: engine-location
Missing Values Count: False    204
Name: engine-location, dtype: int64
============================
Column Name: wheel-base
Missing Values Count: False    204
Name: wheel-base, dtype: int64
============================
Column Name: length
Missing Values Count: False    204
Name: length, dtype: int64
============================
Column Name: width
Missing Values Count: False    204
Name: width, dtype: int64
============================
Column Name: height
Missing Values Count: False    204
Name: height, dtype: int64
============================
Column Name: curb-weight
Missing Values Count: False    204
Name: curb-weight, dtype: int64
============================
Column Name: engine-type
Missing Values Count: False    204
Name: engine-type, dtype: int64
============================
Column Name: num-of-cylinders
Missing Values Count: False    204
Name: num-of-cylinders, dtype: int64
============================
Column Name: engine-size
Missing Values Count: False    204
Name: engine-size, dtype: int64
============================
Column Name: fuel-system
Missing Values Count: False    204
Name: fuel-system, dtype: int64
============================
Column Name: bore
Missing Values Count: False    200
True       4
Name: bore, dtype: int64
============================
Column Name: stroke
Missing Values Count: False    200
True       4
Name: stroke, dtype: int64
============================
Column Name: compression-ratio
Missing Values Count: False    204
Name: compression-ratio, dtype: int64
============================
Column Name: horsepower
Missing Values Count: False    202
True       2
Name: horsepower, dtype: int64
============================
Column Name: peak-rpm
Missing Values Count: False    202
True       2
Name: peak-rpm, dtype: int64
============================
Column Name: city-mpg
Missing Values Count: False    204
Name: city-mpg, dtype: int64
============================
Column Name: highway-mpg
Missing Values Count: False    204
Name: highway-mpg, dtype: int64
============================
Column Name: price
Missing Values Count: False    200
True       4
Name: price, dtype: int64

In [20]:
df['num-of-doors'].value_counts() # Check the value counts for 'num-of-doors' column

four    114
two      88
Name: num-of-doors, dtype: int64

In [21]:
df['num-of-doors'].value_counts().idxmax() # Get the most frequent value for 'num-of-doors' column

'four'

In [22]:
df['num-of-doors'].value_counts().argmax() # Deprecated method to get the most frequent value

0

In [31]:
df['num-of-doors'] = df['num-of-doors'].replace(
    to_replace=np.nan,
    value=df['num-of-doors'].value_counts().idxmax()
) # Fill missing values in 'num-of-doors' with the most frequent value 

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [11]:
df['city_l/100km'] = 235 / df['city-mpg'] # Create a new column 'city_l/100km' by converting 'city-mpg' to liters per 100 kilometers
df['highway_l/100km'] = 235 / df['highway-mpg'] # Create a new column 'highway_l/100km' by converting 'highway-mpg' to liters per 100 kilometers

df[['make', 'city-mpg', 'city_l/100km']] # Display the 'make', 'city-mpg', and 'city_l/100km' columns to verify the new columns have been added correctly

            make  city-mpg  city_l/100km
0    alfa-romero        21     11.190476
1    alfa-romero        19     12.368421
2           audi        24      9.791667
3           audi        18     13.055556
4           audi        19     12.368421
..           ...       ...           ...
199        volvo        23     10.217391
200        volvo        19     12.368421
201        volvo        18     13.055556
202        volvo        26      9.038462
203        volvo        19     12.368421

[204 rows x 3 columns]

In [10]:
df[['length', 'width', 'height']].describe() # Get summary statistics for 'length', 'width', and 'height' columns

           length       width      height
count  204.000000  204.000000  204.000000
mean   174.075000   65.916667   53.749020
std     12.362123    2.146716    2.424901
min    141.100000   60.300000   47.800000
25%    166.300000   64.075000   52.000000
50%    173.200000   65.500000   54.100000
75%    183.200000   66.900000   55.500000
max    208.100000   72.300000   59.800000

In [12]:
df['length'] = df['length'] / df['length'].max() # Normalize 'length' column by dividing each value by the maximum value in the 'length' column
df['width']  = df['width']  / df['width'].max() # Normalize 'width' column by dividing each value by the maximum value in the 'width' column
df['height'] = df['height'] / df['height'].max() # Normalize 'height' column by dividing each value by the maximum value in the 'height' column

df[['length', 'width', 'height']]

       length     width    height
0    0.811148  0.886584  0.816054
1    0.822681  0.905947  0.876254
2    0.848630  0.915629  0.908027
3    0.848630  0.918396  0.908027
4    0.851994  0.917012  0.887960
..        ...       ...       ...
199  0.907256  0.952974  0.928094
200  0.907256  0.951591  0.928094
201  0.907256  0.952974  0.928094
202  0.907256  0.952974  0.928094
203  0.907256  0.952974  0.928094

[204 rows x 3 columns]

In [13]:
dummy_variable_df = pd.get_dummies(df['fuel-type'], dtype='float') # Create dummy variables for 'fuel-type' column and convert them to float type

dummy_variable_df

     diesel  gas
0       0.0  1.0
1       0.0  1.0
2       0.0  1.0
3       0.0  1.0
4       0.0  1.0
..      ...  ...
199     0.0  1.0
200     0.0  1.0
201     0.0  1.0
202     1.0  0.0
203     0.0  1.0

[204 rows x 2 columns]