In [109]:
import pandas as pd # importing the pandas library and giving it an alias 'pd' for easier reference in the code
import numpy as np # importing the numpy library and giving it an alias 'np' for easier reference in the code
import matplotlib.pyplot as plt # importing the matplotlib library and giving it an alias 'plt' for easier reference in the code

In [110]:
df_movie = pd.read_csv(filepath_or_buffer="data/movies.csv") # reading the movies.csv file from the data folder and storing it in a dataframe called df_movie

df_movie.head() # displaying the first few rows of the dataframe

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [111]:
df_movie.shape # displaying the shape of the dataframe, which is the number of rows and columns in the dataframe

(34208, 3)

In [112]:
df_movie.info() # displaying the information about the dataframe, including the number of non-null values in each column and the data type of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34208 entries, 0 to 34207
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  34208 non-null  int64
 1   title    34208 non-null  object
 2   genres   34208 non-null  object
dtypes: int64(1), object(2)
memory usage: 801.9+ KB

In [113]:
df_movie['year'] = df_movie['title'].str.extract(
                                                pat=r'(\d{4})',  # using a regular expression pattern that matches four digits to extract the year from the title column and creating a new column called year in the dataframe
                                                expand=False # using the str.extract() method to extract the year from the title column using a regular expression pattern that matches four digits and creating a new column called year in the dataframe
                                                ) # extracting the year from the title column and creating a new column called year in the dataframe

df_movie.head()

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995

In [114]:
df_movie['title'] = df_movie['title'].str.replace(
    pat=r'(\W{1}\d{4}\W{1})', # regex pattern to match the year in the title column which is a four-digit number surrounded by non-word characters to ensure that we only match the year and not any other four-digit numbers that may be present in the title column and using 
    repl=' ', # replacing the year with a space in the title column to remove the year from the title column and using 
    regex=True # specifying that the pattern is a regex pattern 
) # removing the year from the title column and replacing it with a space and updating the title column in the dataframe to have the modified titles without the year and we will use this modified title column for our analysis of the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the title column after removing the year from it 

df_movie['title'] = df_movie['title'].apply(lambda x: x.strip()) # using the apply() method to apply a lambda function that removes leading and trailing whitespace from the title column and updating the title column in the dataframe to have the modified titles without leading and trailing whitespace and we will use this modified title column for our analysis of the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the title column after removing leading and trailing whitespace from it 

df_movie.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [115]:
df_movie_copy = df_movie.copy() # creating a copy of the original dataframe to work with and avoid modifying the original dataframe in case we need to refer back to it later or if we want to compare the modified dataframe with the original dataframe at any point in the code

df_movie_copy.head() # displaying the first few rows of the copied dataframe to confirm that we have successfully created a copy of the original dataframe and to see the contents of the copied dataframe before making any modifications to it

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [116]:
for index, column in df_movie.iterrows(): # iterating through the dataframe using the iterrows() method which returns an iterator yielding index and column data for each row in the dataframe
    print(index) # printing the index of the current row
    print(column) # printing the data of the current row
    break # breaking the loop after the first iteration to avoid printing all the rows in the dataframe

0
movieId                                              1
title                                        Toy Story
genres     Adventure|Animation|Children|Comedy|Fantasy
year                                              1995
Name: 0, dtype: object

In [117]:
movies_genres_list = [] # creating an empty list to store the genres of the movies in the dataframe and we will use this list to create a list of all the genres of the movies in the dataframe by iterating through the dataframe and splitting the genres column by the '|' character to get a list of genres for each movie and appending the genres of each movie to the movies_genres_list list to create a list of all the genres of the movies in the dataframe and we will use this list to get the unique genres of the movies in the dataframe by using the numpy unique() method to get the unique genres from the movies_genres_list list and storing it in a variable called unique_genres to get the unique genres of the movies in the dataframe and we will also delete the first element of the unique_genres array, which is an empty string that was created when we split the genres column by the '|' character and there were some movies that had no genres listed in the genres column, which resulted in an empty string being added to the movies_genres_list list when we split the genres column by the '|' character and we want to remove that empty string from the unique_genres array to get the correct unique genres of the movies in the dataframe and we will display the unique genres of the movies in the dataframe to see the unique genres of the movies in the dataframe

# Path I
for index, column in df_movie.iterrows(): # iterating through the dataframe using the iterrows() method which returns an iterator yielding index and column data for each row in the dataframe and storing the index and column data in the variables index and column respectively and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column and iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable column: 
    for genre in column['genres'].split('|'): # splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie and storing the genre in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre: 
        movies_genres_list.append(genre) # appending the genres of each movie to the movies_genres_list list to create a list of all the genres of the movies in the dataframe

unique_genres = np.unique(movies_genres_list) # using the numpy unique() method to get the unique genres from the movies_genres_list list and storing it in a variable called unique_genres to get the unique genres of the movies in the dataframe 
unique_genres = np.delete(unique_genres, [0]) # deleting the first element of the unique_genres array, which is an empty string that was created when we split the genres column by the '|' character and there were some movies that had no genres listed in the genres column, which resulted in an empty string being added to the movies_genres_list list when we split the genres column by the '|' character and we want to remove that empty string from the unique_genres array to get the correct unique genres of the movies in the dataframe

unique_genres # displaying the unique genres of the movies in the dataframe

array(['Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'], dtype='<U18')

In [118]:
# Path II
unique_genres = (
    df_movie['genres'] # accessing the genres column of the dataframe and performing the following operations on it 
        .str.split('|') # splitting the genres column by the '|' character to get a list of genres for each movie and creating a new column called genres_list with the list of genres for each movie
        .explode() # exploding the list of genres into separate rows so that each genre is in a separate row and creating a new column called genre with the exploded genres and we will use this column to get the unique genres of the movies in the dataframe by using the numpy unique() method to get the unique genres from the genre column and storing it in a variable called unique_genres to get the unique genres of the movies in the dataframe and we will also delete the first element of the unique_genres array, which is an empty string that was created when we split the genres column by the '|' character and there were some movies that had no genres listed in the genres column, which resulted in an empty string being added to the movies_genres_list list when we split the genres column by the '|' character and we want to remove that empty string from the unique_genres array to get the correct unique genres of the movies in the dataframe and we will display the unique genres of the movies in the dataframe to see the unique genres of the movies in the dataframe
        .unique() # getting the unique genres from the genre column and creating a new column called unique_genres with the unique genres 
        .tolist() # converting the unique genres to a list 
) # displaying the unique genres 

unique_genres

['Adventure',
 'Animation',
 'Children',
 'Comedy',
 'Fantasy',
 'Romance',
 'Drama',
 'Action',
 'Crime',
 'Thriller',
 'Horror',
 'Mystery',
 'Sci-Fi',
 'IMAX',
 'Documentary',
 'War',
 'Musical',
 'Western',
 'Film-Noir',
 '(no genres listed)']

In [119]:
# Path III
unique_genres = df_movie['genres'].str.split('|').sum() # splitting the genres column by the '|' character to get a list of genres for each movie and summing the lists to get a single list of all the genres of the movies in the dataframe and storing it in a variable called unique_genres to get the unique genres of the movies in the dataframe and we will use this list to get the unique genres of the movies in the dataframe by using the numpy unique() method to get the unique genres from the unique_genres list and storing it in a variable called unique_genres to get the unique genres of the movies in the dataframe and we will also delete the first element of the unique_genres array, which is an empty string that was created when we split the genres column by the '|' character and there were some movies that had no genres listed in the genres column, which resulted in an empty string being added to the movies_genres_list list when we split the genres column by the '|' character and we want to remove that empty string from the unique_genres array to get the correct unique genres of the movies in the dataframe and we will display the unique genres of the movies in the dataframe to see the unique genres of the movies in the dataframe 
unique_genres = list(set(unique_genres)) # converting the list of genres to a set to get unique genres and then converting it back to a list to get the unique genres of the movies in the dataframe and we will also delete the first element of the unique_genres list, which is an empty string that was created when we split the genres column by the '|' character and there were some movies that had no genres listed in the genres column, which resulted in an empty string being added to the movies_genres_list list when we split the genres column by the '|' character and we want to remove that empty string from the unique_genres list to get the correct unique genres of the movies in the dataframe and we will display the unique genres of the movies in the dataframe to see the unique genres of the movies in the dataframe 

unique_genres

['Children',
 'Musical',
 'Action',
 'Film-Noir',
 'Thriller',
 'Sci-Fi',
 'Romance',
 'Western',
 '(no genres listed)',
 'IMAX',
 'Drama',
 'Crime',
 'Comedy',
 'Mystery',
 'Fantasy',
 'Animation',
 'War',
 'Adventure',
 'Horror',
 'Documentary']

In [120]:
df_movie = df_movie.assign(**{col: np.nan for col in unique_genres}) # assigning new columns to the dataframe for each unique genre and initializing them with NaN values 

df_movie.head()

,movieId,title,genres,year,Children,Musical,Action,Film-Noir,Thriller,Sci-Fi,...,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Jumanji,Adventure|Children|Fantasy,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Grumpier Old Men,Comedy|Romance,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Father of the Bride Part II,Comedy,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
df_movie.columns

Index(['movieId', 'title', 'genres', 'year', 'Children', 'Musical', 'Action',
       'Film-Noir', 'Thriller', 'Sci-Fi', 'Romance', 'Western',
       '(no genres listed)', 'IMAX', 'Drama', 'Crime', 'Comedy', 'Mystery',
       'Fantasy', 'Animation', 'War', 'Adventure', 'Horror', 'Documentary'],
      dtype='object')

In [122]:
df_movie.head()

,movieId,title,genres,year,Children,Musical,Action,Film-Noir,Thriller,Sci-Fi,...,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Jumanji,Adventure|Children|Fantasy,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Grumpier Old Men,Comedy|Romance,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Father of the Bride Part II,Comedy,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
df_movie.dtypes

movieId                 int64
title                  object
genres                 object
year                   object
Children              float64
Musical               float64
Action                float64
Film-Noir             float64
Thriller              float64
Sci-Fi                float64
Romance               float64
Western               float64
(no genres listed)    float64
IMAX                  float64
Drama                 float64
Crime                 float64
Comedy                float64
Mystery               float64
Fantasy               float64
Animation             float64
War                   float64
Adventure             float64
Horror                float64
Documentary           float64
dtype: object

In [124]:
for index, row in df_movie.iterrows(): # iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable row and iterating through the list of genres for each movie by splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and updating the value in the dataframe for each genre column to 1 if the movie belongs to that genre by using the loc[] method to access the specific cell in the dataframe based on the index and genre and setting its value to 1 if the movie belongs to that genre 
    for genre in row['genres'].split('|'): # splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and updating the value in the dataframe for each genre column to 1 if the movie belongs to that genre by using the loc[] method to access the specific cell in the dataframe based on the index and genre and setting its value to 1 if the movie belongs to that genre 
        df_movie.loc[index, genre] = 1 # iterating through the dataframe using the iterrows() method to access each row of the dataframe and store the data of each row in the variable row and iterating through the list of genres for each movie by splitting the genres column by the '|' character to get a list of genres for each movie and iterating through the list of genres for each movie to access each genre of each movie and store it in the variable genre and updating the value in the dataframe for each genre column to 1 if the movie belongs to that genre by using the loc[] method to access the specific cell in the dataframe based on the index and genre and setting its value to 1 if the movie belongs to that genre 

df_movie.head()

,movieId,title,genres,year,Children,Musical,Action,Film-Noir,Thriller,Sci-Fi,...,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN,NaN
1,2,Jumanji,Adventure|Children|Fantasy,1995,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN
2,3,Grumpier Old Men,Comedy|Romance,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Father of the Bride Part II,Comedy,1995,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
df_movie.fillna(value=0, inplace=True) # filling the NaN values in the dataframe with 0 using the fillna() method and specifying inplace=True to modify the original dataframe and we will use this to indicate that a movie does not belong to a particular genre by filling the NaN values with 0 in the columns for each genre and we will use 1 to indicate that a movie belongs to a particular genre and we will use this information to analyze the genres of the movies in the dataframe and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after filling the NaN values with 0

df_movie.head()

,movieId,title,genres,year,Children,Musical,Action,Film-Noir,Thriller,Sci-Fi,...,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
1,2,Jumanji,Adventure|Children|Fantasy,1995,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,3,Grumpier Old Men,Comedy|Romance,1995,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II,Comedy,1995,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [126]:
# df_movie = (
#     df_movie
#         .join(df_movie['genres'].str.get_dummies('|') # using the str.get_dummies() method to get the dummy variables for each genre by splitting the genres column by the '|' character and creating new columns for each genre with 1s and 0s indicating whether a movie belongs to that genre or not and we will use this to create new columns for each genre with 1s and 0s indicating whether a movie belongs to that genre or not and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after joining it with the new dataframe created by using the str.get_dummies() method to get the dummy variables for each genre
#         .drop(columns='genres')
# ) # joining the original dataframe with the new dataframe created by using the str.get_dummies() method to get the dummy variables for each genre and we will use this to create new columns for each genre with 1s and 0s indicating whether a movie belongs to that genre or not and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after joining it with the new dataframe created by using the str.get_dummies() method to get the dummy variables for each genre

# df_movie.head()

In [127]:
df_user_input = pd.DataFrame([
    {'title': 'Toy Story', 'rating': 5},
    {'title': 'Jumanji', 'rating': 5},
    {'title': 'Father of the Bride Part II', 'rating': 5},
    {'title': 'Space Jam', 'rating': 5},
    {'title': 'Heat', 'rating': 5}
])

df_user_input

                         title  rating
0                    Toy Story       5
1                      Jumanji       5
2  Father of the Bride Part II       5
3                    Space Jam       5
4                         Heat       5

In [128]:
# user_movies = df_user_input.merge(df_movie, on='title', how='left')

df_merge = pd.merge(
    right=df_user_input, 
    left=df_movie_copy, 
    on='title', 
    how='inner'
)

df_merge

,movieId,title,genres,year,rating
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,5
1,2,Jumanji,Adventure|Children|Fantasy,1995,5
2,5,Father of the Bride Part II,Comedy,1995,5
3,6,Heat,Action|Crime|Thriller,1995,5
4,73608,Heat,Comedy|Drama|Romance,1972,5
5,131274,Heat,Action|Drama|Thriller,1986,5
6,673,Space Jam,Adventure|Animation|Children|Comedy|Fantasy|Sc...,1996,5

In [129]:
# df_merge.drop(
#     index=[5,6], # specifying the index of the rows we want to drop from the dataframe by using the index parameter and passing a list with the index of the rows we want to drop and using
#     axis=0, # specifying that we want to drop rows from the dataframe by using axis=0 and specifying the index of the rows we want to drop in a list and using
#     inplace=True # specifying that we want to modify the original dataframe by using inplace=True to drop the rows with index 5 and 6 from the merged dataframe to remove the rows with NaN values in the year column which were created when we merged the user input dataframe with the original dataframe and we will use this modified dataframe to analyze the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after dropping the rows with index 5 and 6
# ) # dropping the rows with index 5 and 6 from the merged dataframe to remove the rows with NaN values in the year column which were created when we merged the user input dataframe with the original dataframe and we will use this modified dataframe to analyze the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after dropping the rows with index 5 and 6

df_merge.drop_duplicates(
    subset=['title'], # specifying that we want to drop duplicate rows based on the title column by using the subset parameter and passing a list with the name of the column we want to use for identifying duplicate rows and using
    inplace=True # specifying that we want to modify the original dataframe by using inplace=True to drop the duplicate rows from the merged dataframe based on the title column to get a dataframe with unique movie titles and we will use this dataframe to analyze the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after dropping the duplicate rows based on the title column
) # dropping the duplicate rows from the merged dataframe based on the title column to get a dataframe with unique movie titles and we will use this dataframe to analyze the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after dropping the duplicate rows based on the title column

In [130]:
df_merge.drop(
    columns=['genres', 'year'], # specifying the columns we want to drop from the dataframe by using the columns parameter and passing a list with the name of the columns we want to drop and using
    axis=1, # specifying that we want to drop columns from the dataframe by using axis=1 and specifying the columns we want to drop in a list and using
    inplace=True # specifying that we want to modify the original dataframe by using inplace=True to drop the genres and year columns from the merged dataframe to remove the unnecessary columns that we don't need for our analysis of the movies that the user has rated and we will use this modified dataframe to analyze the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after dropping the genres and year columns
) # dropping the genres and year columns from the merged dataframe using the drop() method and specifying the columns to drop in a list and specifying axis=1 to indicate that we want to drop columns and specifying inplace=True to modify the original dataframe and we will use this modified dataframe to analyze the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after dropping the genres and year columns

df_merge

   movieId                        title  rating
0        1                    Toy Story       5
1        2                      Jumanji       5
2        5  Father of the Bride Part II       5
3        6                         Heat       5
6      673                    Space Jam       5

In [131]:
df_user_favorite_genres = pd.merge(
    left=df_merge,
    right=df_movie,    
    on='movieId',
    how='inner'
) # merging the modified merged dataframe with the movie dataframe on the movieId column using an inner join to create a new dataframe called df_user_favorite_genres that contains only the movies that the user has rated and we will use this dataframe to analyze the genres of the movies that the user has rated and we will also display the first few rows of the df_user_favorite_genres dataframe to see the changes made to the dataframe after merging it with the movie dataframe on the movieId column using an inner join

df_user_favorite_genres

,movieId,title_x,rating,title_y,genres,year,Children,Musical,Action,Film-Noir,...,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
0,1,Toy Story,5,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
1,2,Jumanji,5,Jumanji,Adventure|Children|Fantasy,1995,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,5,Father of the Bride Part II,5,Father of the Bride Part II,Comedy,1995,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6,Heat,5,Heat,Action|Crime|Thriller,1995,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,673,Space Jam,5,Space Jam,Adventure|Animation|Children|Comedy|Fantasy|Sc...,1996,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [132]:
df_user_favorite_genres = df_user_favorite_genres[unique_genres] # selecting only the columns for the unique genres from the df_user_favorite_genres dataframe to create a new dataframe with only the genre columns and we will use this dataframe to analyze the genres of the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after selecting only the columns for the unique genres

df_user_favorite_genres

,Children,Musical,Action,Film-Noir,Thriller,Sci-Fi,Romance,Western,(no genres listed),IMAX,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [133]:
df_user_favorite_genres.shape # displaying the shape of the df_user_favorite_genres dataframe to see the number of rows and columns in the dataframe and we will use this information to understand the size of the dataframe and to check if we have successfully created a new dataframe with only the genre columns for the movies that the user has rated and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after selecting only the columns for the unique genres

(5, 20)

In [134]:
user_profile_matrix = df_user_favorite_genres.transpose() # transposing the df_user_favorite_genres dataframe to create a new dataframe called user_profile_matrix where the rows represent the genres and the columns represent the movies that the user has rated and we will use this user_profile_matrix dataframe to analyze the genres of the movies that the user has rated and we will also display the first few rows of the user_profile_matrix dataframe to see the changes made to the dataframe after transposing it to create the user_profile_matrix dataframe where the rows represent the genres and the columns represent the movies that the user has rated 

user_profile_matrix

                      0    1    2    3    4
Children            1.0  1.0  0.0  0.0  1.0
Musical             0.0  0.0  0.0  0.0  0.0
Action              0.0  0.0  0.0  1.0  0.0
Film-Noir           0.0  0.0  0.0  0.0  0.0
Thriller            0.0  0.0  0.0  1.0  0.0
Sci-Fi              0.0  0.0  0.0  0.0  1.0
Romance             0.0  0.0  0.0  0.0  0.0
Western             0.0  0.0  0.0  0.0  0.0
(no genres listed)  0.0  0.0  0.0  0.0  0.0
IMAX                0.0  0.0  0.0  0.0  0.0
Drama               0.0  0.0  0.0  0.0  0.0
Crime               0.0  0.0  0.0  1.0  0.0
Comedy              1.0  0.0  1.0  0.0  1.0
Mystery             0.0  0.0  0.0  0.0  0.0
Fantasy             1.0  1.0  0.0  0.0  1.0
Animation           1.0  0.0  0.0  0.0  1.0
War                 0.0  0.0  0.0  0.0  0.0
Adventure           1.0  1.0  0.0  0.0  1.0
Horror              0.0  0.0  0.0  0.0  0.0
Documentary         0.0  0.0  0.0  0.0  0.0

In [135]:
user_profile_matrix = df_user_favorite_genres.transpose().dot(df_merge['rating'].reset_index(drop=True)) # using the dot() method to perform a matrix multiplication between the user_profile_matrix dataframe and the rating column of the df_merge dataframe to create a new dataframe called user_profile_matrix where the values represent the weighted sum of the genres for each movie that the user has rated and we will use this user_profile_matrix dataframe to analyze the genres of the movies that the user has rated and we will also display the first few rows of the modified user_profile_matrix dataframe to see the changes made to the dataframe after performing the matrix multiplication to create a new dataframe where the values represent the weighted sum of the genres for each movie that the user has rated

user_profile_matrix

Children              15.0
Musical                0.0
Action                 5.0
Film-Noir              0.0
Thriller               5.0
Sci-Fi                 5.0
Romance                0.0
Western                0.0
(no genres listed)     0.0
IMAX                   0.0
Drama                  0.0
Crime                  5.0
Comedy                15.0
Mystery                0.0
Fantasy               15.0
Animation             10.0
War                    0.0
Adventure             15.0
Horror                 0.0
Documentary            0.0
dtype: float64

In [136]:
movie_matrix = df_movie.drop(
    columns=['title', 'genres', 'year', '(no genres listed)'], # specifying the columns we want to drop from the dataframe by using the columns parameter and passing a list with the name of the columns we want to drop and using
    axis=1 # specifying that we want to drop columns from the dataframe by using axis=1 and specifying the columns we want to drop in a list and using 
) # dropping the unnecessary columns from the movies_df dataframe to create a new dataframe called movie_matrix that contains only the genre columns and we will use this movie_matrix dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after dropping the unnecessary columns 

movie_matrix.head()

,movieId,Children,Musical,Action,Film-Noir,Thriller,Sci-Fi,Romance,Western,IMAX,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
1,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [137]:
movie_matrix.set_index(
    keys=['movieId'], # specifying the column we want to set as the index of the dataframe by using the keys parameter and passing a list with the name of the column we want to set as the index and using
    inplace=True # specifying that we want to modify the original dataframe by using inplace=True to set the movieId column as the index of the movie_matrix dataframe and we will use this modified dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after setting the movieId column as the index
) # setting the movieId column as the index of the movie_matrix dataframe using the set_index() method and specifying the keys parameter to indicate which column we want to set as the index and specifying inplace=True to modify the original dataframe and we will use this modified dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after setting the movieId column as the index

movie_matrix.head()

,Children,Musical,Action,Film-Noir,Thriller,Sci-Fi,Romance,Western,IMAX,Drama,Crime,Comedy,Mystery,Fantasy,Animation,War,Adventure,Horror,Documentary
movieId,,,,,,,,,,,,,,,,,,,
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [138]:
recomendation_matrix = pd.DataFrame(
    (movie_matrix * user_profile_matrix).sum(axis=1) / user_profile_matrix.sum() # performing a matrix multiplication between the movie_matrix dataframe and the user_profile_matrix dataframe to get the weighted sum of the genres for each movie and then dividing it by the sum of the user_profile_matrix to get the average rating for each genre for each movie and creating a new dataframe called recomendation_matrix with the average rating for each genre for each movie and we will use this recomendation_matrix dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the recomendation_matrix dataframe to see the changes made to the dataframe after performing the matrix multiplication and division to create a new dataframe with the average rating for each genre for each movie
) # creating a new dataframe called recomendation_matrix by performing a matrix multiplication between the movie_matrix dataframe and the user_profile_matrix dataframe to get the weighted sum of the genres for each movie and then dividing it by the sum of the user_profile_matrix to get the average rating for each genre for each movie and we will use this recomendation_matrix dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the recomendation_matrix dataframe to see the changes made to the dataframe after performing the matrix multiplication and division to create a new dataframe with the average rating for each genre for each movie

recomendation_matrix

                0
movieId
1        0.777778
2        0.500000
3        0.166667
4        0.166667
5        0.166667
...           ...
151697   0.055556
151701   0.000000
151703   0.000000
151709   0.055556
151711   0.000000

[34208 rows x 1 columns]

In [139]:
recomendation_matrix.columns = ['weighted_avg'] # renaming the column of the recomendation_matrix dataframe to 'weighted_avg' to indicate that the values in the column represent the weighted average rating for each genre for each movie and we will use this modified dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the modified dataframe to see the changes made to the dataframe after renaming the column to 'weighted_avg' to indicate that the values in the column represent the weighted average rating for each genre for each movie

recomendation_matrix

         weighted_avg
movieId
1            0.777778
2            0.500000
3            0.166667
4            0.166667
5            0.166667
...               ...
151697       0.055556
151701       0.000000
151703       0.000000
151709       0.055556
151711       0.000000

[34208 rows x 1 columns]

In [140]:
recomendation_matrix.sort_values(
    by='weighted_avg', # specifying the column we want to sort the dataframe by using the by parameter and passing the name of the column we want to sort by and using
    ascending=False, # specifying that we want to sort the dataframe in descending order by using the ascending parameter and setting it to False to get the movies with the highest weighted average rating for each genre at the top of the dataframe and using
    inplace=True # specifying that we want to modify the original dataframe in place by using the inplace parameter and setting it to True to avoid creating a new dataframe and using
) # sorting the recomendation_matrix dataframe by the 'weighted_avg' column in descending order to get the movies with the highest weighted average rating for each genre at the top of the dataframe and we will use this sorted dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the sorted dataframe to see the changes made to the dataframe after sorting it by the 'weighted_avg' column in descending order to get the movies with the highest weighted average rating for each genre at the top of the dataframe

recomendation_matrix.head()

         weighted_avg
movieId
2987         0.833333
51632        0.833333
108932       0.833333
32031        0.833333
51939        0.833333

In [141]:
df_result = pd.merge(
    left=df_movie_copy, # specifying the left dataframe we want to merge by using the left parameter and passing the name of the dataframe we want to merge and using
    right=recomendation_matrix, # specifying the right dataframe we want to merge by using the right parameter and passing the name of the dataframe we want to merge and using
    how='inner', # specifying the type of merge we want to perform by using the how parameter and setting it to 'inner' to perform an inner join and using
    on='movieId' # specifying the column we want to merge the dataframes on by using the on parameter and passing the name of the column we want to merge on and using
) # merging the df_movie_copy dataframe with the recomendation_matrix dataframe on the movieId column using an inner join to create a new dataframe called df_result that contains the movie titles and their corresponding weighted average ratings for each genre and we will use this df_result dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the df_result dataframe to see the changes made to the dataframe after merging it with the recomendation_matrix dataframe on the movieId column using an inner join

df_result.head()

,movieId,title,genres,year,weighted_avg
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,0.777778
1,2,Jumanji,Adventure|Children|Fantasy,1995,0.500000
2,3,Grumpier Old Men,Comedy|Romance,1995,0.166667
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995,0.166667
4,5,Father of the Bride Part II,Comedy,1995,0.166667

In [143]:
df_result.sort_values(
    by='weighted_avg', # specifying the column we want to sort the dataframe by using the by parameter and passing the name of the column we want to sort by and using
    ascending=False, # specifying that we want to sort the dataframe in descending order by using the ascending parameter and setting it to False to get the movies with the highest weighted average rating for each genre at the top of the dataframe and using
    inplace=True # specifying that we want to modify the original dataframe in place by using the inplace parameter and setting it to True to avoid creating a new dataframe and using
) # sorting the df_result dataframe by the 'weighted_avg' column in descending order to get the movies with the highest weighted average rating for each genre at the top of the dataframe and we will use this sorted dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the sorted dataframe to see the changes made to the dataframe after sorting it by the 'weighted_avg' column in descending order to get the movies with the highest weighted average rating for each genre at the top of the dataframe

df_result.head(20)

,movieId,title,genres,year,weighted_avg
2902,2987,Who Framed Roger Rabbit?,Adventure|Animation|Children|Comedy|Crime|Fant...,1988,0.833333
22881,108932,The Lego Movie,Action|Adventure|Animation|Children|Comedy|Fan...,2014,0.833333
9825,32031,Robots,Adventure|Animation|Children|Comedy|Fantasy|Sc...,2005,0.833333
11751,51939,TMNT (Teenage Mutant Ninja Turtles),Action|Adventure|Animation|Children|Comedy|Fan...,2007,0.833333
8783,26340,"Twelve Tasks of Asterix, The (Les douze travau...",Action|Adventure|Animation|Children|Comedy|Fan...,1976,0.833333
664,673,Space Jam,Adventure|Animation|Children|Comedy|Fantasy|Sc...,1996,0.833333
28220,130520,Home,Adventure|Animation|Children|Comedy|Fantasy|Sc...,2015,0.833333
11716,51632,Atlantis: Milo's Return,Action|Adventure|Animation|Children|Comedy|Fan...,2003,0.833333
24273,114240,Aladdin,Adventure|Animation|Children|Comedy|Fantasy,1992,0.777778
3923,4016,"Emperor's New Groove, The",Adventure|Animation|Children|Comedy|Fantasy,2000,0.777778
10375,36397,Valiant,Adventure|Animation|Children|Comedy|Fantasy|War,2005,0.777778
24343,114552,"Boxtrolls, The",Adventure|Animation|Children|Comedy|Fantasy,2014,0.777778
15429,78499,Toy Story 3,Adventure|Animation|Children|Comedy|Fantasy|IMAX,2010,0.777778
18317,91355,Asterix and the Vikings (Astérix et les Vikings),Adventure|Animation|Children|Comedy|Fantasy,2006,0.777778
15453,78637,Shrek Forever After (a.k.a. Shrek: The Final C...,Adventure|Animation|Children|Comedy|Fantasy|IMAX,2010,0.777778
29963,136361,Scooby-Doo! Mask of the Blue Falcon,Adventure|Animation|Children|Comedy|Fantasy,2012,0.777778
11883,53121,Shrek the Third,Adventure|Animation|Children|Comedy|Fantasy,2007,0.777778
4791,4886,"Monsters, Inc.",Adventure|Animation|Children|Comedy|Fantasy,2001,0.777778
542,546,Super Mario Bros.,Action|Adventure|Children|Comedy|Fantasy|Sci-Fi,1993,0.777778
8605,26093,"Wonderful World of the Brothers Grimm, The",Adventure|Animation|Children|Comedy|Drama|Fant...,1962,0.777778