In [1]:
import pandas as pd
from math import sqrt

In [2]:
movies_df = pd.read_csv(
    filepath_or_buffer='data/movies.csv'
)

ratings_df = pd.read_csv(
    filepath_or_buffer='data/ratings.csv'
)

In [3]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
ratings_df.head()

   userId  movieId  rating   timestamp
0       1      169     2.5  1204927694
1       1     2471     3.0  1204927438
2       1    48516     5.0  1204927435
3       2     2571     3.5  1436165433
4       2   109487     4.0  1436165496

In [ ]:
movies_df['year'] = movies_df['title'].str.extract(pat=r'(\d{4})', expand=False) # extracting the year from the title column of the movies_df dataframe using a regular expression pattern that matches four digits and creating a new column called 'year' in the movies_df dataframe to store the extracted year values and we will use this new 'year' column to analyze the release years of the movies in the dataframe and we will also display the first few rows of the movies_df dataframe to see the changes made to the dataframe after extracting the year from the title column and creating a new 'year' column to store the extracted year values and we will also check the data types of the columns in the movies_df dataframe to see if the 'year' column is of the correct data type for analysis and we will also display the first few rows of the movies_df dataframe to see the changes made to the dataframe after checking the data types of the columns in the movies_df dataframe to see if the 'year' column is of the correct data type for analysis and we will also display the first few rows of the movies_df dataframe to see the changes made to the dataframe after extracting the year from the title column and creating a new 'year' column to store the extracted year values and checking the data types of the columns in the movies_df dataframe to see if the 'year' column is of the correct data type for analysis

movies_df.head()

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995

In [7]:
movies_df['title'] = movies_df['title'].str.replace(pat=r'(\W{1}\d{4}\W{1})', repl='', regex=True) # removing the year from the title column of the movies_df dataframe using a regular expression pattern that matches a non-word character followed by four digits followed by a non-word character and replacing it with an empty string to remove the year from the title column and we will use this modified title column to analyze the movie titles in the dataframe and we will also display the first few rows of the movies_df dataframe to see the changes made to the dataframe after removing the year from the title column and we will also check the data types of the columns in the movies_df dataframe to see if the modified title column is of the correct data type for analysis and we will also display the first few rows of the movies_df dataframe to see the changes made to the dataframe after checking the data types of the columns in the movies_df dataframe to see if the modified title column is of the correct data type for analysis and we will also display the first few rows of the movies_df dataframe to see the changes made to the dataframe after removing the year from the title column and checking the data types of the columns in the movies_df dataframe to see if the modified title column is of the correct data type for analysis

movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [8]:
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())

movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [13]:
ratings_df.drop(
    columns=['timestamp'], # specifying the column we want to drop from the ratings_df dataframe by using the columns parameter and passing a list of column names we want to drop and using
    axis=1, # specifying that we want to drop a column from the ratings_df dataframe by using the axis parameter and setting it to 1 to indicate that we want to drop a column and using
    inplace=True # specifying that we want to modify the original dataframe in place by using the inplace parameter and setting it to True to avoid creating a new dataframe and using
) # dropping the 'timestamp' column from the ratings_df dataframe using the drop method and specifying the column to drop using the columns parameter and setting axis to 1 to indicate that we want to drop a column and setting inplace to True to modify the original dataframe in place and we will use this modified ratings_df dataframe to analyze the ratings of the movies in the dataframe and we will also display the first few rows of the ratings_df dataframe to see the changes made to the dataframe after dropping the 'timestamp' column and we will also check the data types of the columns in the ratings_df dataframe to see if the modified ratings_df dataframe is of the correct data type for analysis and we will also display the first few rows of the ratings_df dataframe to see the changes made to the dataframe after checking the data types of the columns in the ratings_df dataframe to see if the modified ratings_df dataframe is of the correct data type for analysis and we will also display the first few rows of the ratings_df dataframe to see the changes made to the dataframe after dropping the 'timestamp' column and checking the data types of the columns in the ratings_df dataframe to see if the modified ratings_df dataframe is of the correct data type for analysis 

ratings_df.head()

   userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

In [9]:
ratings_df.shape

(22884377, 4)

In [10]:
user_input_df = pd.DataFrame([
    {'title': 'Toy Story', 'rating': 5},
    {'title': 'Jumanji', 'rating': 5},
    {'title': 'Home', 'rating': 5},
    {'title': 'Space Jam', 'rating': 5},
    {'title': 'Who Framed Roger Rabbit?', 'rating': 5}
])

user_input_df

                      title  rating
0                 Toy Story       5
1                   Jumanji       5
2                      Home       5
3                 Space Jam       5
4  Who Framed Roger Rabbit?       5

In [ ]:
merged_df = pd.merge(
    right=user_input_df, # specifying the right dataframe we want to merge by using the right parameter and passing the name of the dataframe we want to merge and using
    left=movies_df, # specifying the left dataframe we want to merge by using the left parameter and passing the name of the dataframe we want to merge and using
    how='inner', # specifying the type of merge we want to perform by using the how parameter and setting it to 'inner' to perform an inner join and using
    on='title' # specifying the column we want to merge the dataframes on by using the on parameter and passing the name of the column we want to merge on and using
) # merging the movies_df dataframe with the user_input_df dataframe on the title column using an inner join to create a new dataframe called merged_df that contains the movie titles and their corresponding ratings from the user_input_df dataframe and we will use this merged_df dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the merged_df dataframe to see the changes made to the dataframe after merging it with the user_input_df dataframe on the title column using an inner join

merged_df

,movieId,title,genres,year,rating
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,5
1,2,Jumanji,Adventure|Children|Fantasy,1995,5
2,673,Space Jam,Adventure|Animation|Children|Comedy|Fantasy|Sc...,1996,5
3,2987,Who Framed Roger Rabbit?,Adventure|Animation|Children|Comedy|Crime|Fant...,1988,5
4,69529,Home,Documentary,2009,5
5,79254,Home,Drama,2008,5
6,130520,Home,Adventure|Animation|Children|Comedy|Fantasy|Sc...,2015,5
7,143972,Home,(no genres listed),2013,5
8,143974,Home,Drama,2011,5

In [12]:
merged_df.drop(
    index=[4, 5, 7, 8],
    axis=0,
    inplace=True
)

merged_df

,movieId,title,genres,year,rating
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995,5
1,2,Jumanji,Adventure|Children|Fantasy,1995,5
2,673,Space Jam,Adventure|Animation|Children|Comedy|Fantasy|Sc...,1996,5
3,2987,Who Framed Roger Rabbit?,Adventure|Animation|Children|Comedy|Crime|Fant...,1988,5
6,130520,Home,Adventure|Animation|Children|Comedy|Fantasy|Sc...,2015,5

In [14]:
user_subset_df = pd.merge(
    left=ratings_df, # specifying the left dataframe we want to merge by using the left parameter and passing the name of the dataframe we want to merge and using
    right=merged_df, # specifying the right dataframe we want to merge by using the right parameter and passing the name of the dataframe we want to merge and using
    how='inner', # specifying the type of merge we want to perform by using the how parameter and setting it to 'inner' to perform an inner join and using 
    on='movieId' # specifying the column we want to merge the dataframes on by using the on parameter and passing the name of the column we want to merge on and using  
) # merging the ratings_df dataframe with the merged_df dataframe on the movieId column using an inner join to create a new dataframe called user_subset_df that contains the movie titles and their corresponding ratings from the ratings_df dataframe for the movies that are in the merged_df dataframe and we will use this user_subset_df dataframe to analyze the genres of the movies in the dataframe and we will also display the first few rows of the user_subset_df dataframe to see the changes made to the dataframe after merging it with the merged_df dataframe on the movieId column using an inner join

print(f'Shape: {user_subset_df.shape}')

user_subset_df.head()

Shape: (119049, 7)

,userId,movieId,rating_x,title,genres,year,rating_y
0,13,2,2.0,Jumanji,Adventure|Children|Fantasy,1995,5
1,17,2,3.0,Jumanji,Adventure|Children|Fantasy,1995,5
2,34,2,2.5,Jumanji,Adventure|Children|Fantasy,1995,5
3,40,2,5.0,Jumanji,Adventure|Children|Fantasy,1995,5
4,75,2,3.5,Jumanji,Adventure|Children|Fantasy,1995,5